spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sprint_risk}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    enabled: true
